### ISSUE TITLE
Feature Request - Automatically add requests

### ISSUE THREAD

**Issue by rguyor2** [OpenKJ/OpenKJ#34] opened 2018-01-03 21:38 UTC
This system is great, thank you for your amazing work on it. I just started using it for doing karaoke at home. One feature I'd love to see is when people send in a song request via the songbook.openkj.org page, it would automatically add them to the rotation. This way rather than having to be there to do KJ duties, anyone in the house could submit a request, get added to the rotation and sing as soon as they come up. I guess part of that would also be a feature to automatically start the rotation when there are songs in the queue. I'm sure this isn't something needed by pro KJs out there, but it'd be great for home users.

thanks!

**Comment by coyote1357** [comment] 2018-01-08 05:02
This isn't a "no", but it may be a while before this gets implemented.  The problem is that most KJs will have multiple versions of the same song, and the songbook site automatically deduplicates these and only shows one entry without the discid info.  OpenKJ would currently have no idea which version to use, and randomly picking would be less than ideal. There will either need to be an option added to the songbook site to show all versions individually, some sort of prioritized karaoke vendor list in OpenKJ for use in automatically selecting tracks, or both.  And yes, it would also necessitate modifying audoplay to start back up if it's currently in an idle state due to a lack of pending songs queued.

**Comment by frogonwheels** [comment] 2018-07-21 00:11
I'm using OpenKJ for a home environment with a small song selection, so I would quite like this feature and wouldn't mind giving it a go.  The option could actually be a combo - with choices like:

- Manual (current behaviour)
- Auto add if unambiguous (If there's a choice, leave it for the operator)
- Auto with Smart Match  (Use heuristics to work out the probable best match)
  - Which song has been played more
  - ?? 

Another idea (further to your point about showing all versions) - would be to be able to edit the database entry for a song - and maybe even have an additional field for comments.  Then you would be able to show a sub-title on the website that would have comments helping you or the user to choose between the songs. You could also have an integer 'score' field that would help with the heuristics.  That way you could score 1 song as a 5 and another as an 8 , but if you got a new, better version of the song, you could score it a 10 so that it got selected.

**Comment by frogonwheels** [comment] 2018-07-21 01:34
The song score could also be used to order the songs in the web interface! (Highest at the top)

**Comment by vaccinemedia** [comment] 2019-03-29 16:15
KJams on the Mac has this feature - the song request app shows you all the versions of a particular song you have searched for and the end user simply selects which version they want. Some seasoned singers will already know which version they want by the brand (SF, DK, ZOOM etc...) it means that there are more options showing / available to pick from but that's a necessary evil I think. I've been to bars in the past where in their songbooks (printed) they have separate entries for each version of a particular song they have. This would in effect enable bars to have a karaoke jukebox setup which autoplays the background music and then plays the next upcoming singer if anyone has entered one. Simple instructions on how to use the request app would then be all that's needed.

**Comment by vaccinemedia** [comment] 2019-03-29 21:21
In fact OpenKJ has just been featured in this month's issue (April 2019) of MagPi magazine so a fair few pi enthusiasts may be checking it out and so a "kiosk mode" is going to be a much sought after feature. The pi only having a hdmi out to the TV will benefit from the ability to use the request apps to add songs to the rotation negating the need for a KJ view / monitor / screen.
https://www.raspberrypi.org/magpi-issues/MagPi80.pdf

**Comment by backstagekaraoke** [comment] 2021-04-03 16:10
Both these request will be getting addressed in my upcoming #233

**Closed by backstagekaraoke** 2021-04-03 16:10 UTC
Labels: feature request

**Comment by Dachaz** [comment] 2025-03-05 13:12
Hey @backstagekaraoke — I see this marked as completed, but I'm not seeing the #233 you're referring to, nor the option to Automatically add requests in the latest OpenKJ. If relevant, I tried this against [StandaloneRequestServer](https://github.com/OpenKJ/StandaloneRequestServer).

What I do see are multiple versions of the same song when searching on the Server, reflecting what I have in the library (and reading the comments here, that seems not to have been the case before). Anyway, I'd love to have the full self-service as we intend to run this one-off on our wedding, and we'd definitely prefer not having to have someone behind the laptop to accept the requests.

Thanks!

**Comment by SchmalzTech** [comment] 2025-03-05 16:04
Sadly, development and maintenance of OpenKJ has pretty much stopped since ILightburn passed away. I use it, but I am not very proficient in any sort of coding, and I hope someone more capable than me finds this awesome project and picks it up. There were a couple of builds since he passed, but I run 2.0.8 because the 2.1 builds I have tried all had stability issues, at least in Windows. I believe I built newer commits from source on a Linux based machine and it was good.

**Comment by vaccinemedia** [comment] 2025-03-05 16:10
@Dachaz seeing as this is for your wedding I hope it's OK to recommend an alternative: https://github.com/vicwomg/pikaraoke

You can install it on a Mac, Windows or RaspberryPi (anything which can run Python). I have personally used it on my MacBook Pro and a RaspberryPi 4 and 5 (Pi 5 needs a cheap Berhinger USB audio device) to connect to the mixer.

Once it starts the splash screen is displayed along with a QR Code you can scan to enter your name and add your requests. It starts with zero songs but downloads them on the fly so you can get going with zero tunes if you don't have any. They have just added filler mp3 support and mp4 video splash screens too.

Hope your wedding is totally awesome!

**Comment by Dachaz** [comment] 2025-03-05 16:14
Thanks @vaccinemedia, this looks perfect!
