### ISSUE TITLE
Bug: OpenKJ - Ticker singers not clearing on Clear Song DB

### ISSUE THREAD

**Issue by backstagekaraoke** [OpenKJ/OpenKJ#160] opened 2019-03-15 07:46 UTC
OpenKJ 1.5.33
Windows 10 64bit

Scenario

1. Update All currently doesn't remove songs from the DB when the files have been removed, so you have to do a Clear Song DB then an Update All to build the DB again.

2. Ticker was configured with "Performing now is %curSinger - Next Singer is %nextSinger"

3. Had existing singers in the rotation

Issue
I cleared the DB using Clear Song DB
The singers and songs cleared, however on the main screen under the song search box, it still kept a trace of a singer, so it still listed 'Song Queue - Terri S' even though it should have been cleared.

Went to the ticker and it read 'Performing now None - Next Singer is Justin U" - Justin was the next singer after Terri S in the rotation before I cleared the DB

Additional information

After a restart of OpenKJ information displayed:

"Song Queue - (No Singer Selected)" - Normal
"Performing now None - Next singer is None" - Normal

Seems like OKJ isn't doing a complete clear of the DB, until its restarted.

**Comment by coyote1357** [comment] 2019-04-30 15:10
Well, the db itself is being fully cleared, the signals/slots that tell those UI components that they need to update to the current state just aren't firing. If you added a new singer it would force a ticker update and clicking on a new singer would clear the stale queue data. Definitely will fix though, as that could be confusing and isn't the intended behaviour.

**Comment by coyote1357** [comment] 2019-05-01 00:38
Should be fixed in 1.5.51 unstable

**Closed** 2019-06-26 23:12 UTC
Labels: Fix pending verification, bug
